---
- name: Display the welcome message
  vars:
    helloMessage: |
      ------------------------------------------------------------------------------------------------------------------------------------------------------
      Time to learn how to search files and delete it.
      grep
      look at the txt file, and find how many time "John Garcia" is present
      then execute the script "script.sh" to get the password of the next user
      -----------------------------------------------------------------------------------------------------------------------------------------------------
  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/.bashrc
    line: 'clear;echo "{{ helloMessage }}";'
    create: yes

- name: Create the script
  ansible.builtin.file:
    path: /home/{{ currentUser }}/script.sh
    state: touch
    owner: "{{ currentUser }}"
    group: "{{ currentUser }}"
    mode: '0755'

- name: Copy file "fileEx7.txt" to the home
  ansible.builtin.copy:
    src: files/fileEx7.txt
    dest: /home/{{ currentUser }}/names.txt
    owner: "{{ currentUser }}"
    mode: '0644'

- name: Write the script
  vars:
    script: |
      read -r -p "How Many John Garcia? " COUNT </dev/tty; [ "$COUNT" -eq 118 ] && echo "password: $(echo YmxhOA== | base64 -d)" || echo "Try again"

  ansible.builtin.copy:
    dest: /home/{{ currentUser }}/.encoded_script.sh
    content: "{{ script | b64encode }}"
    owner: "{{ currentUser }}"
    group: "{{ currentUser }}"
    mode: '0600'

- name: Create the wrapper script to decode and execute
  ansible.builtin.copy:
    dest: /home/{{ currentUser }}/script.sh
    content: |
      #!/bin/bash
      base64 -d /home/{{ currentUser }}/.encoded_script.sh | bash -s
    owner: "{{ currentUser }}"
    mode: '0755'
