- hosts: localhost
  become: yes
  vars:
    users:
      - { name: 'ex1', password: 'bla' }
      - { name: 'ex2', password: 'bla2' }
      - { name: 'ex3', password: 'bla3' }
      - { name: 'ex4', password: 'bla4' }
      - { name: 'ex5', password: 'YmxhNQ==' }
      - { name: 'ex6', password: 'bla6' }
      - { name: 'ex7', password: 'bla7' }
      - { name: 'ex8', password: 'bla8' }
      - { name: 'ex9', password: 'bla9' }
      - { name: 'ex10', password: 'bla10' }

  tasks:
    - name: Creation des Users
      include_role:
        name: addUsers

    - name: Ajout du message de bienvenue sur le user start (creer par le Dockerfile)
      include_role:
        name: helloMessage

    - name: Parametrage exercie1
      include_role:
        name: ex1
      vars:
        currentUser: "{{ users[0].name }}"
        nextUser: "{{ users[1].name }}"
        nextUserPassword: "{{ users[1].password }}"
    
    - name: Parametrage exercie2
      include_role:
        name: ex2
      vars:
        currentUser: "{{ users[1].name }}"
        nextUser:  "{{ users[2].name }}"
        nextUserPassword: "{{ users[2].password }}"
      
    - name: Parametrage exercie3
      include_role:
        name: ex3
      vars:
        currentUser: "{{ users[2].name }}"
        nextUser:  "{{ users[3].name }}"
        nextUserPassword: "{{ users[3].password }}"
 
    - name: Parametrage exercie4
      include_role:
        name: ex4
      vars:
        currentUser: "{{ users[3].name }}"
        nextUser:  "{{ users[4].name }}"
        nextUserPassword: "{{ users[4].password }}"
        
