---

- name: Display the welcome message
  vars:
    helloMessage: |
      ------------------------------------------------------------------------------------------------------------------------------------------------------
      
      unique 
      look at the txt file and remove the duplicate names
      then execute the script "script.sh" to get the password of the next user
      -----------------------------------------------------------------------------------------------------------------------------------------------------
  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/.bashrc
    line: 'clear;echo "{{ helloMessage }}";'
    create: yes

- name: Create the script
  ansible.builtin.file:
    path: /home/{{ currentUser }}/script.sh
    state: touch
    owner: "{{ currentUser }}"
    mode: '0755'

- name: copy file "fileEx8.txt" to the home
  ansible.builtin.copy:
    src: files/fileEx8.txt
    dest: /home/{{ currentUser }}/names.txt
    owner: "{{ currentUser }}"
    mode: '0755'

- name: Write the script
  vars:
    script: |
      read -p "How Many names in the files without duplicates ? " COUNT </dev/tty; [ "$COUNT" -eq 100 ] && echo -e "------------------\npassword: $(echo {{ nextUserPassword }} | base64 --decode)\n------------------" || echo -e "------------------\nTry again\n------------------"

  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/.encoded_script.sh
    line: '{{ script | b64encode }}'
    create: yes

- name: Create the wrapper script to decode and execute
  ansible.builtin.copy:
    dest: /home/{{ currentUser }}/script.sh
    content: |
      #!/bin/bash
      base64 -d /home/{{ currentUser }}/.encoded_script.sh | bash
    owner: "{{ currentUser }}"
    mode: '0755'