---

- name: Display the welcome message
  vars:
    helloMessage: |
      ------------------------------------------------------------------------------------------------------------------------------------------------------
      Time to learn how to search files and delete it.
      unique 
      look at the txt file and remove the duplicate names
      then execute the script "script.sh" to get the password of the next user
      -----------------------------------------------------------------------------------------------------------------------------------------------------
  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/.bashrc
    line: 'clear;echo "{{ helloMessage }}";'
    create: yes

- name: Create the script
  ansible.builtin.file:
    path: /home/{{ currentUser }}/script.sh
    state: touch
    owner: "{{ currentUser }}"
    mode: '0755'

- name: copy file "fileEx8.txt" to the home
  ansible.builtin.copy:
    src: files/fileEx8.txt
    dest: /home/{{ currentUser }}/names.txt
    owner: "{{ currentUser }}"
    mode: '0755'

- name: Write the script
  vars:
    script: |
      #!/bin/bash
      read -p "How Many names in the files without duplicates' ? " COUNT
      if [ $COUNT -eq 100 ]; then
        echo "------------------"
        echo password: $(echo "{{ nextUserPassword }}" | base64 --decode)
        echo "------------------"
      else
        echo "------------------"
        echo "Try again"
        echo "------------------"
      fi
  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/script.sh
    line: '{{ script }}'
    create: yes