---

- name: Display the welcome message
  vars:
    helloMessage: |
      ------------------------------------------------------------------------------------------------------------------------------------------------------
      Time to learn how to create and edit files.
      "touch"
      "nano"
      create a file named: "truc.txt"
      use nano to edit the file, write "hello world" inside and save it
      then execute the script "script.sh" to get the password of the next user
      -----------------------------------------------------------------------------------------------------------------------------------------------------
  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/.bashrc
    line: 'clear;echo "{{ helloMessage }}";'
    create: yes

- name: Create the script
  ansible.builtin.file:
    path: /home/{{ currentUser }}/script.sh
    state: touch
    owner: "{{ currentUser }}"
    mode: '0755'

- name: Write the script
  vars:
    script: |
      #!/bin/bash
      file="truc.txt"
      if [ -f "$file" ] && grep -q "hello world" "$file"; then
        echo "------------------"
        echo "$file is present."
        echo password: $(echo "{{ nextUserPassword }}" | base64 --decode)
        echo "------------------"
      else
        echo "One or both files are missing."
      fi
  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/.encoded_script.sh
    line: '{{ script | b64encode }}'
    create: yes

- name: Create the wrapper script to decode and execute
  ansible.builtin.copy:
    dest: /home/{{ currentUser }}/script.sh
    content: |
      #!/bin/bash
      base64 -d /home/{{ currentUser }}/.encoded_script.sh | bash
    owner: "{{ currentUser }}"
    mode: '0755'