---
# tasks file for addUsers
- name: Add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    create_home: yes
    password: "{{ item.password | password_hash('sha512') }}"
  become: true
  loop: "{{ users }}"

- name: Force to cd to home directory for each user
  ansible.builtin.lineinfile:
    path: "/home/{{ item.name }}/.bashrc"
    line: 'cd ~'
    create: yes
    state: present
  loop: "{{ users }}"

