---

- name: Display the welcome message
  vars:
    helloMessage: |
      -----------------------------------------------------------------------------------------------------------------------------------------------------
      Well done, your first Linux command, I'm proud of you.
      Let's learn two new commands:
      "ls": to list all the files and folders inside the one you are currently in.
      "cat": to read the content of a file.
      Use the password to connect to the next user/exercise: {{ nextUser }}
      -----------------------------------------------------------------------------------------------------------------------------------------------------

  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/.bashrc
    line: 'clear; echo "{{ helloMessage }}";'
    create: yes

- name: Create a file
  ansible.builtin.file:
    path: /home/{{ currentUser }}/password.txt
    state: touch
    owner: "{{ currentUser }}"
    mode: '0644'

- name: Add content to the file
  ansible.builtin.lineinfile:
    path: /home/{{ currentUser }}/password.txt
    line: '{{ nextUserPassword }}'
    create: yes
